query GetCarts($getCartsInput: GetCartsInput!) {
  carts(getCartsInput: $getCartsInput) {
    id
    cartItems {
      id
      name
      unit_size
      price
      upc1
      upc2
      nacs_category
      nacs_subcategory
      quantity
      item_id
    }
    subtotal
  }
}
