query GetItems($getItemsInput: GetItemsInput) {
  items(getItemsInput: $getItemsInput) {
    id
    name
    unit_size
    price
    upc1
    upc2
    nacs_category
    nacs_subcategory
    image
  }
}
