query GetOrders($getOrdersInput: GetOrdersInput) {
  orders(getOrdersInput: $getOrdersInput) {
    id
    status
    subtotal
    date_submitted
    orderItems {
      id
      name
      unit_size
      price
      upc1
      upc2
      nacs_category
      nacs_subcategory
      quantity
      item_id
      image
    }
  }
}
