query GetOrders($getOrdersInput: GetOrdersInput) {
  orders(getOrdersInput: $getOrdersInput) {
    id
    status
    subtotal
    date_submitted
    orderItems {
      id
      sku
      description
      sell_size
      unit_size
      case_cost
      profit_margin
      srp
      upc1
      upc2
      nacs_category
      nacs_subcategory
      quantity
      item_id
      image
    }
  }
}